from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app.application.factory import get_pipeline_service
from app.schemas import MCPRequest

router = APIRouter()


def _tools() -> list[dict]:
    return [
        {
            "name": "start_pipeline",
            "description": "Start the Xiaohongshu pipeline and return its workflow summary.",
            "inputSchema": {
                "type": "object",
                "properties": {
                    "keywords": {"type": "array", "items": {"type": "string"}},
                    "min_likes": {"type": "integer"},
                    "min_favorites": {"type": "integer"},
                    "min_comments": {"type": "integer"},
                    "auto_publish": {"type": "boolean"},
                    "dry_run": {"type": "boolean"},
                },
                "required": ["keywords"],
            },
        },
        {"name": "list_drafts", "description": "List current generated drafts.", "inputSchema": {"type": "object", "properties": {}}},
        {"name": "list_runs", "description": "List recorded pipeline runs and their status.", "inputSchema": {"type": "object", "properties": {}}},
        {"name": "list_publish_jobs", "description": "List recorded publish jobs and their status.", "inputSchema": {"type": "object", "properties": {}}},
        {"name": "list_source_posts", "description": "List source posts collected by the pipeline.", "inputSchema": {"type": "object", "properties": {"run_id": {"type": "string"}}}},
        {"name": "list_analysis_reports", "description": "List analysis reports generated by the pipeline.", "inputSchema": {"type": "object", "properties": {"run_id": {"type": "string"}}}},
        {"name": "list_topic_suggestions", "description": "List generated topic suggestions.", "inputSchema": {"type": "object", "properties": {"run_id": {"type": "string"}}}},
        {"name": "list_image_assets", "description": "List generated image assets.", "inputSchema": {"type": "object", "properties": {"run_id": {"type": "string"}}}},
        {"name": "get_source_post", "description": "Get a single source post by id.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
        {"name": "get_analysis_report", "description": "Get a single analysis report by id.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
        {"name": "get_topic_suggestion", "description": "Get a single topic suggestion by id.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
        {"name": "get_image_asset", "description": "Get a single image asset by id.", "inputSchema": {"type": "object", "properties": {"id": {"type": "string"}}, "required": ["id"]}},
        {"name": "start_collector_search", "description": "Start a Scrapling-backed search collection run.", "inputSchema": {"type": "object", "properties": {"keywords": {"type": "array", "items": {"type": "string"}}, "dry_run": {"type": "boolean"}}, "required": ["keywords"]}},
        {"name": "start_collector_detail", "description": "Start a Scrapling-backed detail collection run.", "inputSchema": {"type": "object", "properties": {"note_ids": {"type": "array", "items": {"type": "string"}}, "dry_run": {"type": "boolean"}}, "required": ["note_ids"]}},
        {"name": "start_sync_run", "description": "Start a sync run through the configured sync provider.", "inputSchema": {"type": "object", "properties": {"entity_type": {"type": "string"}, "payload": {"type": "object"}, "dry_run": {"type": "boolean"}}, "required": ["entity_type", "payload"]}},
        {"name": "list_collector_runs", "description": "List collector runs.", "inputSchema": {"type": "object", "properties": {}}},
        {"name": "list_sync_runs", "description": "List sync runs.", "inputSchema": {"type": "object", "properties": {}}},
        {"name": "get_provider_status", "description": "Return provider diagnostics and health summaries.", "inputSchema": {"type": "object", "properties": {}}},
    ]


@router.post("/mcp")
def handle_mcp(request: MCPRequest) -> dict:
    if request.method == "initialize":
        return {"jsonrpc": "2.0", "id": request.id, "result": {"serverInfo": {"name": "xhs-platform-mcp", "version": "0.2.0"}}}
    if request.method == "tools/list":
        return {"jsonrpc": "2.0", "id": request.id, "result": {"tools": _tools()}}
    if request.method == "tools/call":
        params = request.params or {}
        name = params.get("name")
        arguments = params.get("arguments", {})
        service = get_pipeline_service()
        if name == "start_pipeline":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.create_run(arguments)}
        if name == "list_runs":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_runs()}
        if name == "list_drafts":
            return {"jsonrpc": "2.0", "id": request.id, "result": {"items": service.list_drafts()}}
        if name == "list_publish_jobs":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_publish_jobs()}
        if name == "list_source_posts":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_source_posts(arguments.get("run_id"))}
        if name == "list_analysis_reports":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_analysis_reports(arguments.get("run_id"))}
        if name == "list_topic_suggestions":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_topic_suggestions(arguments.get("run_id"))}
        if name == "list_image_assets":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_image_assets(arguments.get("run_id"))}
        if name == "get_source_post":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.get_source_post(arguments["id"])}
        if name == "get_analysis_report":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.get_analysis_report(arguments["id"])}
        if name == "get_topic_suggestion":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.get_topic_suggestion(arguments["id"])}
        if name == "get_image_asset":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.get_image_asset(arguments["id"])}
        if name == "start_collector_search":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.start_collector_run(arguments, "search")}
        if name == "start_collector_detail":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.start_collector_run(arguments, "detail")}
        if name == "start_sync_run":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.start_sync_run(arguments["entity_type"], arguments["payload"], arguments.get("dry_run", True))}
        if name == "list_collector_runs":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_collector_runs()}
        if name == "list_sync_runs":
            return {"jsonrpc": "2.0", "id": request.id, "result": service.list_sync_runs()}
        if name == "get_provider_status":
            return {"jsonrpc": "2.0", "id": request.id, "result": {"diagnostics": service.provider_diagnostics(), "health": service.provider_health()}}
        raise HTTPException(status_code=404, detail=f"Unknown tool: {name}")
    raise HTTPException(status_code=400, detail=f"Unsupported MCP method: {request.method}")
